/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NFCardEmulationDelegate, OS_dispatch_queue;
@class NSObject;

@interface NFCardEmulation : NSObject {

	bool _ceEnable;
	bool _fieldDetectEnable;
	unsigned char _source;
	id<NFCardEmulationDelegate> _delegate;
	NSObject*<OS_dispatch_queue> _callbackQueue;

}
-(void)dealloc;
-(void)_didReceiveEvent:(id)arg1 ;
-(void)_startCardEmulation;
-(void)_stopCardEmulation;
-(void)_startFieldDetect;
-(void)_stopFieldDetect;
-(id)initWithSource:(unsigned char)arg1 delegate:(id)arg2 queue:(id)arg3 ;
-(void)_didCEChangeSuspended:(bool)arg1 ;
-(void)_didFDChangeSuspended:(bool)arg1 ;
-(void)_didDetectField:(bool)arg1 ;
-(void)_didReceiveCardSelect:(id)arg1 ;
-(void)_didStartTransaction:(id)arg1 ;
-(void)_didEndTransaction:(id)arg1 ;
-(void)_didReceiveButtonPressed:(id)arg1 ;
-(void)_didReceiveTimerExpired:(id)arg1 ;
-(void)_didReceiveRestrictedModeChanged:(bool)arg1 ;
-(id)initWithSource:(unsigned char)arg1 delegate:(id)arg2 queue:(id)arg3 idleExit:(bool)arg4 ;
-(void)startCardEmulation;
-(void)stopCardEmulation;
-(void)startFieldDetect;
-(void)stopFieldDetect;
@end

