/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol NFCardManagerEventListenerDelegate <NSObject>
@required
-(void)cardManagerEventListener:(id)arg1 didReceiveRemoteAdminNotification:(id)arg2;
-(void)cardManagerEventListener:(id)arg1 secureElementDidBecomeAvailable:(bool)arg2;
@end

