/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <NearField/NFCardEmulation.h>

@interface NFCardEmulationUEA : NFCardEmulation
-(void)_handleEvent:(id)arg1 ;
-(void)_startCardEmulation;
-(void)_stopCardEmulation;
-(void)_startFieldDetect;
-(void)_stopFieldDetect;
@end

