/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <NearField/XPCConnectionDelegate.h>

@protocol OS_dispatch_queue, NFCardManagerEventListenerDelegate;
@class NSObject, XPCConnection, NSString;

@interface NFCardManagerEventListener : NSObject <XPCConnectionDelegate> {

	bool _idleExit;
	bool _isRegistered;
	NSObject*<OS_dispatch_queue> _callbackQueue;
	XPCConnection* _xpcConnection;
	id<NFCardManagerEventListenerDelegate> _delegate;

}

@property (assign,nonatomic) id<NFCardManagerEventListenerDelegate> delegate;
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(void)setDelegate:(id<NFCardManagerEventListenerDelegate>)arg1 ;
-(id<NFCardManagerEventListenerDelegate>)delegate;
-(id)_getXPCConnection;
-(void)XPCConnectionDidTerminate:(id)arg1 ;
-(void)XPCConnection:(id)arg1 didReceiveEvent:(id)arg2 ;
-(void)XPCConnectionServiceDidRestart:(id)arg1 ;
-(void)_handleUEAEvent:(id)arg1 ;
-(bool)startEventListener;
-(void)stopEventListener;
-(id)initWithDelegate:(id)arg1 queue:(id)arg2 idleExit:(bool)arg3 ;
@end

