/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface NFCard : NSObject {

	unsigned char _family;
	unsigned char _lifecycleState;
	unsigned char _activationState;
	bool _authTransientSupport;
	NSString* _aid;

}

@property (nonatomic,readonly) NSString * aid;
@property (nonatomic,readonly) unsigned char family;
@property (nonatomic,readonly) unsigned char lifecycleState;
@property (nonatomic,readonly) unsigned char activationState;
@property (nonatomic,readonly) bool authTransientSupport;

-(void)dealloc;
-(id)description;
-(id)initWithDictionary:(id)arg1 ;
-(void)setIsActive:(bool)arg1 ;
-(bool)authTransientSupport;
-(unsigned char)family;
-(unsigned char)activationState;
-(unsigned char)lifecycleState;
-(NSString *)aid;
@end

