/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSData;

@interface NFEcommerceTransactionResponse : NSObject {

	NSString* _transactionIdentifier;
	NSData* _transactionData;

}

@property (nonatomic,readonly) NSString * transactionIdentifier;
@property (nonatomic,readonly) NSData * transactionData;

+(id)responseWithInfo:(id)arg1 ;
-(void)dealloc;
-(NSData *)transactionData;
-(NSString *)transactionIdentifier;
@end

