/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSData, NSDecimalNumber, NSDate;

@interface NFECommerceTransactionRequest : NSObject {

	unsigned char _merchantCapabilities;
	unsigned _unpredictableNumber;
	NSString* _applicationIdentifier;
	NSData* _merchantData;
	NSString* _merchantIdentifier;
	NSString* _currencyCode;
	NSString* _countryCode;
	NSDecimalNumber* _transactionAmount;
	NSDate* _transactionDate;

}

@property (nonatomic,retain) NSString * applicationIdentifier;
@property (nonatomic,retain) NSData * merchantData;
@property (nonatomic,retain) NSString * merchantIdentifier;
@property (nonatomic,retain) NSString * currencyCode;
@property (nonatomic,retain) NSString * countryCode;
@property (nonatomic,retain) NSDecimalNumber * transactionAmount;
@property (nonatomic,retain) NSDate * transactionDate;
@property (assign,nonatomic) unsigned char merchantCapabilities;
@property (assign,nonatomic) unsigned unpredictableNumber;

+(id)getCountryCodeTranslationTable;
-(NSDate *)transactionDate;
-(void)setTransactionDate:(NSDate *)arg1 ;
-(NSDecimalNumber *)transactionAmount;
-(void)dealloc;
-(NSString *)applicationIdentifier;
-(id)asDictionary;
-(void)setApplicationIdentifier:(NSString *)arg1 ;
-(NSData *)merchantData;
-(bool)currencyValueConversion:(id)arg1 output:(char*)arg2 maxLen:(int)arg3 fractionDigit:(int)arg4 ;
-(unsigned)unpredictableNumber;
-(NSString *)currencyCode;
-(void)setCurrencyCode:(NSString *)arg1 ;
-(NSString *)merchantIdentifier;
-(void)setMerchantIdentifier:(NSString *)arg1 ;
-(void)setMerchantData:(NSData *)arg1 ;
-(void)setTransactionAmount:(NSDecimalNumber *)arg1 ;
-(unsigned char)merchantCapabilities;
-(void)setMerchantCapabilities:(unsigned char)arg1 ;
-(void)setUnpredictableNumber:(unsigned)arg1 ;
-(void)setCountryCode:(NSString *)arg1 ;
-(NSString *)countryCode;
@end

