/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface NFHardwareSecureElementInfo : NSObject {

	bool _restrictedMode;
	unsigned long long _OSVersion;
	unsigned long long _firmwareVersion;
	unsigned long long _hardwareVersion;
	unsigned long long _deviceType;
	unsigned long long _sequenceCounter;
	unsigned long long _referenceCounter;
	unsigned long long _osid;
	unsigned long long _otherOSValid;
	unsigned long long _OSMode;
	unsigned long long _signingKeyType;
	unsigned long long _migrationState;
	unsigned long long _migrationPackages;
	unsigned long long _migrationInstances;
	NSString* _platformIdentifier;
	NSString* _serialNumber;

}

@property (nonatomic,readonly) unsigned long long OSVersion;
@property (nonatomic,readonly) unsigned long long firmwareVersion;
@property (nonatomic,readonly) unsigned long long hardwareVersion;
@property (nonatomic,readonly) unsigned long long deviceType;
@property (nonatomic,readonly) unsigned long long sequenceCounter;
@property (nonatomic,readonly) unsigned long long referenceCounter;
@property (nonatomic,readonly) unsigned long long osid;
@property (nonatomic,readonly) unsigned long long otherOSValid;
@property (nonatomic,readonly) bool restrictedMode;
@property (nonatomic,readonly) unsigned long long OSMode;
@property (nonatomic,readonly) unsigned long long signingKeyType;
@property (nonatomic,readonly) unsigned long long migrationState;
@property (nonatomic,readonly) unsigned long long migrationPackages;
@property (nonatomic,readonly) unsigned long long migrationInstances;
@property (nonatomic,readonly) NSString * platformIdentifier;
@property (nonatomic,readonly) NSString * serialNumber;

-(void)dealloc;
-(id)initWithDictionary:(id)arg1 ;
-(NSString *)serialNumber;
-(unsigned long long)OSVersion;
-(unsigned long long)firmwareVersion;
-(unsigned long long)sequenceCounter;
-(unsigned long long)referenceCounter;
-(unsigned long long)osid;
-(unsigned long long)otherOSValid;
-(bool)restrictedMode;
-(unsigned long long)OSMode;
-(unsigned long long)signingKeyType;
-(unsigned long long)migrationState;
-(unsigned long long)migrationPackages;
-(unsigned long long)migrationInstances;
-(NSString *)platformIdentifier;
-(unsigned long long)deviceType;
-(unsigned long long)hardwareVersion;
@end

