/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NFDaemonProxy;

@interface NFHardwareManager : NSObject {

	NFDaemonProxy* _nfcd;

}
+(id)sharedHardwareManager;
-(void)dealloc;
-(id)init;
-(id)getControllerInfo;
-(id)getSecureElementInfo;
-(id)getBoosterInfo;
@end

