/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSDecimalNumber, NSData;

@interface NFTransactionEndEvent : NSObject {

	unsigned short _command;
	unsigned short _status;
	unsigned short _result;
	unsigned short _informative;
	NSString* _aid;
	NSString* _transactionId;
	NSDecimalNumber* _amount;
	NSString* _currency;
	NSData* _tlv;

}

@property (nonatomic,readonly) NSString * aid;
@property (nonatomic,readonly) NSString * transactionId;
@property (nonatomic,readonly) unsigned short command;
@property (nonatomic,readonly) unsigned short status;
@property (nonatomic,readonly) unsigned short result;
@property (nonatomic,readonly) unsigned short informative;
@property (nonatomic,readonly) NSDecimalNumber * amount;
@property (nonatomic,readonly) NSString * currency;
@property (nonatomic,readonly) NSData * tlv;

-(unsigned short)command;
-(void)dealloc;
-(id)description;
-(id)initWithDictionary:(id)arg1 ;
-(NSDecimalNumber *)amount;
-(unsigned short)result;
-(unsigned short)status;
-(NSData *)tlv;
-(NSString *)aid;
-(NSString *)currency;
-(NSString *)transactionId;
-(unsigned short)informative;
@end

