/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface NFTransactionStartEvent : NSObject {

	unsigned short _status;
	NSString* _aid;

}

@property (nonatomic,readonly) NSString * aid;
@property (nonatomic,readonly) unsigned short status;

-(void)dealloc;
-(id)description;
-(id)initWithDictionary:(id)arg1;
-(unsigned short)status;
-(NSString *)aid;
-(id)transactionId;
@end

