/*
* This header is generated by classdump-dyld 0.7
* Operating System: Version 8.1 (Build 12B411)
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol XPCConnectionDelegate <NSObject>
@optional
-(void)XPCConnection:(id)arg1 didReceiveCommand:(id)arg2;
-(void)XPCConnection:(id)arg1 didReceiveEvent:(id)arg2;
-(void)XPCConnectionServiceWillTerminate:(id)arg1;
-(void)XPCConnectionServiceDidRestart:(id)arg1;

@required
-(void)XPCConnectionDidTerminate:(id)arg1;
@end

